apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploymentwithhostpath
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypodforhostpath
  template:
    metadata:
      labels:
        app: mypodforhostpath
    spec:
      containers:
      - name: mynginx
        image: nginx:latest
        ports:
        - containerPort: 80 
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: myhostpathvolume
      volumes:
        - name: myhostpathvolume
          hostPath:
            path: /myhostpath
            type: DirectoryOrCreate

---

kind: Service
apiVersion: v1
metadata:
  name: mypodforhostpathservice
spec:
  selector:
    app: mypodforhostpath
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8080
      nodePort: 30001
